register:
    path: /register
    controller: App\Controller\AuthController::register
    methods: POST

api:
    path: /api
    controller: App\Controller\AuthController::api

login:
    path:     /api/auth/login
    methods:  [POST]

user:
    path: /api/auth/user
    controller: App\Controller\AuthController::me

refresh:
    path: /api/auth/refresh
    controller: App\Controller\AuthController::refresh